import { env } from 'bun'

export default {
	// AWS
	AWS_ACCESS_KEY: env.AWS_ACCESS_KEY || '',
	AWS_SECRET_ACCESS_KEY: env.AWS_SECRET_ACCESS_KEY || '',
	AWS_REGION: env.AWS_REGION || '',
	MAIN_BUCKET: env.MAIN_BUCKET || '',

	// JWT
	JWT_SECRET_KEY: env.JWT_SECRET_KEY || '',
	JWT_EXPIRATION_TIME: env.JWT_EXPIRATION_TIME || '',
	REFRESH_SECRET_KEY: env.REFRESH_SECRET_KEY || '',
	REFRESH_EXPIRATION_TIME: env.REFRESH_EXPIRATION_TIME || '',

	// DATABASE
	DATABASE_URL: env.DATABASE_URL || '',

	// HTTP SERVER
	PORT: parseInt(env.PORT || '', 10),

	// REDIS
	REDIS_PORT: parseInt(env.REDIS_PORT || '6379', 10),
	REDIS_HOST: env.REDIS_HOST || 'localhost',
	CACHE_EXPIRE_TIME: 60 * 60 * 24,
}
